apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: {{ template "fullname" . }}-cosmosdb-binding
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  instanceRef:
    name: {{ .Values.instance.name }} 
  secretName: {{ template "fullname" . }}-cosmosdb-secret
  {{- if .Values.instance.local }}
  secretTransforms:
    - 
      renameKey:
        from: uri
        to: connectionString
  {{- end }}
